#!/usr/bin/env bash
# One-time, permanent setup so the cloudtse hardware TSE (Swissbit TSE on a
# HUAWEI SD_Storage USB stick, vendor:model 12d1:1436) is usable by a
# non-root user (no more `sudo ./start.sh` needed for permissions).
#
# What this does:
#   1. Unmounts any stacked/duplicate previous mounts at /mnt/tse.
#   2. Installs a udev rule that, whenever this specific TSE USB device is
#      plugged in:
#        - grants the `plugdev` group rw access to the raw block device
#          (used as a fallback I/O path by libWormAPI), and
#        - auto-mounts its partition at /mnt/tse owned by uid/gid 1000
#          (adjust MOUNT_UID/MOUNT_GID below if your user isn't uid 1000),
#          and auto-unmounts it on removal.
#   3. Reloads udev rules and re-triggers them for the currently attached
#      device so the fix applies immediately, without a reboot/replug.
#
# Must be run with sudo/root:
#   sudo ./setup-tse-permissions.sh

set -euo pipefail

if [[ "$(id -u)" -ne 0 ]]; then
    echo "Please run this with sudo: sudo $0" >&2
    exit 1
fi

MOUNT_UID="${MOUNT_UID:-1000}"
MOUNT_GID="${MOUNT_GID:-1000}"
VENDOR_ID="12d1"
MODEL_ID="1436"
RULES_FILE="/etc/udev/rules.d/99-cloudtse.rules"

echo "==> Unmounting any stacked previous mounts at /mnt/tse..."
while mountpoint -q /mnt/tse 2>/dev/null; do
    umount /mnt/tse
    echo "    unmounted one layer"
done
echo "    done."

echo "==> Installing udev rule at $RULES_FILE..."
cat >"$RULES_FILE" <<RULES
# cloudtse TSE (USB vendor:model ${VENDOR_ID}:${MODEL_ID}) permissions.
# Grants the plugdev group rw access to the raw block device (fallback
# I/O path for libWormAPI), and auto-mounts/unmounts the TSE partition at
# /mnt/tse owned by uid=${MOUNT_UID},gid=${MOUNT_GID} whenever it is
# plugged in / removed. Generated by setup-tse-permissions.sh.
SUBSYSTEM=="block", ENV{ID_VENDOR_ID}=="${VENDOR_ID}", ENV{ID_MODEL_ID}=="${MODEL_ID}", GROUP="plugdev", MODE="0660"

ACTION=="add", SUBSYSTEM=="block", KERNEL=="sd?1", ENV{ID_VENDOR_ID}=="${VENDOR_ID}", ENV{ID_MODEL_ID}=="${MODEL_ID}", RUN+="/usr/bin/systemd-mount --no-block --collect -o uid=${MOUNT_UID},gid=${MOUNT_GID},fmask=0022,dmask=0022,rw \$env{DEVNAME} /mnt/tse"

ACTION=="remove", SUBSYSTEM=="block", KERNEL=="sd?1", ENV{ID_VENDOR_ID}=="${VENDOR_ID}", ENV{ID_MODEL_ID}=="${MODEL_ID}", RUN+="/usr/bin/systemd-umount /mnt/tse"
RULES
echo "    done."

echo "==> Reloading udev rules..."
udevadm control --reload-rules
echo "    done."

echo "==> Re-triggering udev for the currently attached device..."
udevadm trigger --subsystem-match=block --action=add
sleep 2
echo "    done."

echo "==> Result:"
findmnt /mnt/tse || echo "    (not mounted yet - unplug/replug the TSE stick, or check 'lsusb' / dmesg for the device)"
if mountpoint -q /mnt/tse 2>/dev/null; then
    stat -c '    owner: %U:%G  mode: %a' /mnt/tse
fi

echo ""
echo "Setup complete. You can now run ./start.sh as a normal user (no sudo)."
